//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for AltitudeDepth_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AltitudeDepth_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Not applicable"/>
 *     &lt;enumeration value="Very small"/>
 *     &lt;enumeration value="Small"/>
 *     &lt;enumeration value="Middle"/>
 *     &lt;enumeration value="Large"/>
 *     &lt;enumeration value="Very large"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AltitudeDepth_Type")
@XmlEnum
public enum AltitudeDepthType implements Serializable {


    /**
     * 
     *                         None of the codes in the table are applicable in the context of this particular observation (nilReason)
     *                     
     * 
     */
    @XmlEnumValue("Not applicable")
    NOT_APPLICABLE("Not applicable"),

    /**
     * 
     *                         between -100 m and 100 m
     *                     
     * 
     */
    @XmlEnumValue("Very small")
    VERY_SMALL("Very small"),

    /**
     * 
     *                         Between -300 and -100 m or between 100 and 300 m
     *                     
     * 
     */
    @XmlEnumValue("Small")
    SMALL("Small"),

    /**
     * 
     *                         Between -1000 and -300 m or between 300 and 1000 m
     *                     
     * 
     */
    @XmlEnumValue("Middle")
    MIDDLE("Middle"),

    /**
     * 
     *                         Between -3000 and -1000 m Between 1000 and 3000 m
     *                     
     * 
     */
    @XmlEnumValue("Large")
    LARGE("Large"),

    /**
     * 
     *                         Deeper than -3000 m or above 3000 m
     *                     
     * 
     */
    @XmlEnumValue("Very large")
    VERY_LARGE("Very large");
    private final String value;

    AltitudeDepthType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AltitudeDepthType fromValue(String v) {
        for (AltitudeDepthType c: AltitudeDepthType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
