//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for ApplicationArea_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ApplicationArea_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Global numerical weather prediction (GNWP)"/>
 *     &lt;enumeration value="High-resolution numerical weather prediction (HRNWP)"/>
 *     &lt;enumeration value="Nowcasting and very short range forecasting (NVSRF)"/>
 *     &lt;enumeration value="Seasonal and inter-annual forecasting (SIAF)"/>
 *     &lt;enumeration value="General weather forecasting"/>
 *     &lt;enumeration value="Aeronautical meteorology"/>
 *     &lt;enumeration value="Ocean applications"/>
 *     &lt;enumeration value="Agricultural meteorology"/>
 *     &lt;enumeration value="Hydrology"/>
 *     &lt;enumeration value="Climate monitoring (as undertaken through the Global Climate Observing System, GCOS)"/>
 *     &lt;enumeration value="Climate applications"/>
 *     &lt;enumeration value="Space weather"/>
 *     &lt;enumeration value="Cryosphere applications"/>
 *     &lt;enumeration value="Energy sector"/>
 *     &lt;enumeration value="Transportation sector"/>
 *     &lt;enumeration value="Health sector"/>
 *     &lt;enumeration value="Terrestrial ecology"/>
 *     &lt;enumeration value="Operational air quality forecasting"/>
 *     &lt;enumeration value="Atmospheric composition forecasting"/>
 *     &lt;enumeration value="Atmospheric composition monitoring and analysis"/>
 *     &lt;enumeration value="Large urban complexes"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ApplicationArea_Type")
@XmlEnum
public enum ApplicationAreaType implements Serializable {

    @XmlEnumValue("Global numerical weather prediction (GNWP)")
    GLOBAL_NUMERICAL_WEATHER_PREDICTION_GNWP("Global numerical weather prediction (GNWP)"),
    @XmlEnumValue("High-resolution numerical weather prediction (HRNWP)")
    HIGH_RESOLUTION_NUMERICAL_WEATHER_PREDICTION_HRNWP("High-resolution numerical weather prediction (HRNWP)"),
    @XmlEnumValue("Nowcasting and very short range forecasting (NVSRF)")
    NOWCASTING_AND_VERY_SHORT_RANGE_FORECASTING_NVSRF("Nowcasting and very short range forecasting (NVSRF)"),
    @XmlEnumValue("Seasonal and inter-annual forecasting (SIAF)")
    SEASONAL_AND_INTER_ANNUAL_FORECASTING_SIAF("Seasonal and inter-annual forecasting (SIAF)"),
    @XmlEnumValue("General weather forecasting")
    GENERAL_WEATHER_FORECASTING("General weather forecasting"),
    @XmlEnumValue("Aeronautical meteorology")
    AERONAUTICAL_METEOROLOGY("Aeronautical meteorology"),
    @XmlEnumValue("Ocean applications")
    OCEAN_APPLICATIONS("Ocean applications"),
    @XmlEnumValue("Agricultural meteorology")
    AGRICULTURAL_METEOROLOGY("Agricultural meteorology"),
    @XmlEnumValue("Hydrology")
    HYDROLOGY("Hydrology"),
    @XmlEnumValue("Climate monitoring (as undertaken through the Global Climate Observing System, GCOS)")
    CLIMATE_MONITORING_AS_UNDERTAKEN_THROUGH_THE_GLOBAL_CLIMATE_OBSERVING_SYSTEM_GCOS("Climate monitoring (as undertaken through the Global Climate Observing System, GCOS)"),
    @XmlEnumValue("Climate applications")
    CLIMATE_APPLICATIONS("Climate applications"),
    @XmlEnumValue("Space weather")
    SPACE_WEATHER("Space weather"),
    @XmlEnumValue("Cryosphere applications")
    CRYOSPHERE_APPLICATIONS("Cryosphere applications"),
    @XmlEnumValue("Energy sector")
    ENERGY_SECTOR("Energy sector"),
    @XmlEnumValue("Transportation sector")
    TRANSPORTATION_SECTOR("Transportation sector"),
    @XmlEnumValue("Health sector")
    HEALTH_SECTOR("Health sector"),
    @XmlEnumValue("Terrestrial ecology")
    TERRESTRIAL_ECOLOGY("Terrestrial ecology"),
    @XmlEnumValue("Operational air quality forecasting")
    OPERATIONAL_AIR_QUALITY_FORECASTING("Operational air quality forecasting"),
    @XmlEnumValue("Atmospheric composition forecasting")
    ATMOSPHERIC_COMPOSITION_FORECASTING("Atmospheric composition forecasting"),
    @XmlEnumValue("Atmospheric composition monitoring and analysis")
    ATMOSPHERIC_COMPOSITION_MONITORING_AND_ANALYSIS("Atmospheric composition monitoring and analysis"),
    @XmlEnumValue("Large urban complexes")
    LARGE_URBAN_COMPLEXES("Large urban complexes");
    private final String value;

    ApplicationAreaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ApplicationAreaType fromValue(String v) {
        for (ApplicationAreaType c: ApplicationAreaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
