//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for DataQuality_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataQuality_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="uncertaintyOfMeasurement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="procedureUsedToEstimateUncertainty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="qualityFlag" type="{}QualityFlag_Type"/>
 *         &lt;element name="qualityFlaggingSystem" type="{}QualityFlaggingSystem_Type"/>
 *         &lt;element name="traceability" type="{}Traceability_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataQuality_Type", propOrder = {
    "uncertaintyOfMeasurement",
    "procedureUsedToEstimateUncertainty",
    "qualityFlag",
    "qualityFlaggingSystem",
    "traceability"
})
public class DataQualityType implements Serializable {

    protected String uncertaintyOfMeasurement;
    protected String procedureUsedToEstimateUncertainty;
    @XmlElement(required = true)
    protected QualityFlagType qualityFlag;
    @XmlElement(required = true)
    protected QualityFlaggingSystemType qualityFlaggingSystem;
    @XmlElement(required = true)
    protected TraceabilityType traceability;

    /**
     * Gets the value of the uncertaintyOfMeasurement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUncertaintyOfMeasurement() {
        return uncertaintyOfMeasurement;
    }

    /**
     * Sets the value of the uncertaintyOfMeasurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUncertaintyOfMeasurement(String value) {
        this.uncertaintyOfMeasurement = value;
    }

    /**
     * Gets the value of the procedureUsedToEstimateUncertainty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcedureUsedToEstimateUncertainty() {
        return procedureUsedToEstimateUncertainty;
    }

    /**
     * Sets the value of the procedureUsedToEstimateUncertainty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcedureUsedToEstimateUncertainty(String value) {
        this.procedureUsedToEstimateUncertainty = value;
    }

    /**
     * Gets the value of the qualityFlag property.
     * 
     * @return
     *     possible object is
     *     {@link QualityFlagType }
     *     
     */
    public QualityFlagType getQualityFlag() {
        return qualityFlag;
    }

    /**
     * Sets the value of the qualityFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualityFlagType }
     *     
     */
    public void setQualityFlag(QualityFlagType value) {
        this.qualityFlag = value;
    }

    /**
     * Gets the value of the qualityFlaggingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link QualityFlaggingSystemType }
     *     
     */
    public QualityFlaggingSystemType getQualityFlaggingSystem() {
        return qualityFlaggingSystem;
    }

    /**
     * Sets the value of the qualityFlaggingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualityFlaggingSystemType }
     *     
     */
    public void setQualityFlaggingSystem(QualityFlaggingSystemType value) {
        this.qualityFlaggingSystem = value;
    }

    /**
     * Gets the value of the traceability property.
     * 
     * @return
     *     possible object is
     *     {@link TraceabilityType }
     *     
     */
    public TraceabilityType getTraceability() {
        return traceability;
    }

    /**
     * Sets the value of the traceability property.
     * 
     * @param value
     *     allowed object is
     *     {@link TraceabilityType }
     *     
     */
    public void setTraceability(TraceabilityType value) {
        this.traceability = value;
    }

}
