//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for DataProcessingAndReporting_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataProcessingAndReporting_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dataProcessingMethodsAndAlgorithms" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="processingAnalysisCentre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="temporalReportingPeriod" type="{}MeaningOfTimeStamp_Type"/>
 *         &lt;element name="spatialReportingInterval" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="softwareProcessorAndVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="levelOfData" type="{}LevelOfData_Type" minOccurs="0"/>
 *         &lt;element name="dataFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="versionOfDataFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="aggregationPeriod" type="{}MeaningOfTimeStamp_Type"/>
 *         &lt;element name="referenceTime" type="{}ReferenceTime_Type"/>
 *         &lt;element name="referenceDatum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numericalResolution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="latencyOfReporting" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataProcessingAndReporting_Type", propOrder = {
    "dataProcessingMethodsAndAlgorithms",
    "processingAnalysisCentre",
    "temporalReportingPeriod",
    "spatialReportingInterval",
    "softwareProcessorAndVersion",
    "levelOfData",
    "dataFormat",
    "versionOfDataFormat",
    "aggregationPeriod",
    "referenceTime",
    "referenceDatum",
    "numericalResolution",
    "latencyOfReporting"
})
public class DataProcessingAndReportingType implements Serializable {

    protected String dataProcessingMethodsAndAlgorithms;
    protected String processingAnalysisCentre;
    @XmlElement(required = true)
    protected MeaningOfTimeStampType temporalReportingPeriod;
    protected String spatialReportingInterval;
    protected String softwareProcessorAndVersion;
    protected LevelOfDataType levelOfData;
    @XmlElement(required = true)
    protected String dataFormat;
    @XmlElement(required = true)
    protected String versionOfDataFormat;
    @XmlElement(required = true)
    protected MeaningOfTimeStampType aggregationPeriod;
    @XmlElement(required = true)
    protected ReferenceTimeType referenceTime;
    protected String referenceDatum;
    protected String numericalResolution;
    @XmlElement(required = true)
    protected String latencyOfReporting;

    /**
     * Gets the value of the dataProcessingMethodsAndAlgorithms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataProcessingMethodsAndAlgorithms() {
        return dataProcessingMethodsAndAlgorithms;
    }

    /**
     * Sets the value of the dataProcessingMethodsAndAlgorithms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataProcessingMethodsAndAlgorithms(String value) {
        this.dataProcessingMethodsAndAlgorithms = value;
    }

    /**
     * Gets the value of the processingAnalysisCentre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingAnalysisCentre() {
        return processingAnalysisCentre;
    }

    /**
     * Sets the value of the processingAnalysisCentre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingAnalysisCentre(String value) {
        this.processingAnalysisCentre = value;
    }

    /**
     * Gets the value of the temporalReportingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link MeaningOfTimeStampType }
     *     
     */
    public MeaningOfTimeStampType getTemporalReportingPeriod() {
        return temporalReportingPeriod;
    }

    /**
     * Sets the value of the temporalReportingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeaningOfTimeStampType }
     *     
     */
    public void setTemporalReportingPeriod(MeaningOfTimeStampType value) {
        this.temporalReportingPeriod = value;
    }

    /**
     * Gets the value of the spatialReportingInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpatialReportingInterval() {
        return spatialReportingInterval;
    }

    /**
     * Sets the value of the spatialReportingInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpatialReportingInterval(String value) {
        this.spatialReportingInterval = value;
    }

    /**
     * Gets the value of the softwareProcessorAndVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareProcessorAndVersion() {
        return softwareProcessorAndVersion;
    }

    /**
     * Sets the value of the softwareProcessorAndVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareProcessorAndVersion(String value) {
        this.softwareProcessorAndVersion = value;
    }

    /**
     * Gets the value of the levelOfData property.
     * 
     * @return
     *     possible object is
     *     {@link LevelOfDataType }
     *     
     */
    public LevelOfDataType getLevelOfData() {
        return levelOfData;
    }

    /**
     * Sets the value of the levelOfData property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelOfDataType }
     *     
     */
    public void setLevelOfData(LevelOfDataType value) {
        this.levelOfData = value;
    }

    /**
     * Gets the value of the dataFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataFormat() {
        return dataFormat;
    }

    /**
     * Sets the value of the dataFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataFormat(String value) {
        this.dataFormat = value;
    }

    /**
     * Gets the value of the versionOfDataFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionOfDataFormat() {
        return versionOfDataFormat;
    }

    /**
     * Sets the value of the versionOfDataFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionOfDataFormat(String value) {
        this.versionOfDataFormat = value;
    }

    /**
     * Gets the value of the aggregationPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link MeaningOfTimeStampType }
     *     
     */
    public MeaningOfTimeStampType getAggregationPeriod() {
        return aggregationPeriod;
    }

    /**
     * Sets the value of the aggregationPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeaningOfTimeStampType }
     *     
     */
    public void setAggregationPeriod(MeaningOfTimeStampType value) {
        this.aggregationPeriod = value;
    }

    /**
     * Gets the value of the referenceTime property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceTimeType }
     *     
     */
    public ReferenceTimeType getReferenceTime() {
        return referenceTime;
    }

    /**
     * Sets the value of the referenceTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceTimeType }
     *     
     */
    public void setReferenceTime(ReferenceTimeType value) {
        this.referenceTime = value;
    }

    /**
     * Gets the value of the referenceDatum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceDatum() {
        return referenceDatum;
    }

    /**
     * Sets the value of the referenceDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceDatum(String value) {
        this.referenceDatum = value;
    }

    /**
     * Gets the value of the numericalResolution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumericalResolution() {
        return numericalResolution;
    }

    /**
     * Sets the value of the numericalResolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumericalResolution(String value) {
        this.numericalResolution = value;
    }

    /**
     * Gets the value of the latencyOfReporting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatencyOfReporting() {
        return latencyOfReporting;
    }

    /**
     * Sets the value of the latencyOfReporting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatencyOfReporting(String value) {
        this.latencyOfReporting = value;
    }

}
