//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for DataPolicyUseConstraints_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DataPolicyUseConstraints_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="WMOEssential"/>
 *     &lt;enumeration value="WMOAdditional"/>
 *     &lt;enumeration value="WMOOther"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DataPolicyUseConstraints_Type")
@XmlEnum
public enum DataPolicyUseConstraintsType implements Serializable {


    /**
     * 
     *                         WMO Essential Data: free and unrestricted international exchange of basic data and products.
     *                     
     * 
     */
    @XmlEnumValue("WMOEssential")
    WMO_ESSENTIAL("WMOEssential"),

    /**
     * 
     *                         WMO Additional Data: free and unrestricted access to data and products exchanged under the auspices of WMO to
     *                         the research and education communities for non-commercial activities. A more precise definition of the data policy may
     *                         be additionally supplied within the metadata. In all cases it shall be the responsibility of the data consumer to ensure
     *                         that they understand the data policy specified by the data provider – which may necessitate dialogue with the data
     *                         publisher for confirmation of terms and conditions.
     *                     
     * 
     */
    @XmlEnumValue("WMOAdditional")
    WMO_ADDITIONAL("WMOAdditional"),

    /**
     * 
     *                         Data identified for global distribution via WMO infrastructure (GTS / WIS) that is not covered by WMO Resolution 25
     *                         neither WMO Resolution 40; e.g. aviation OPMET data. Data marked with “WMOOther” data policy shall be treated like
     *                         “WMOAdditional” where a more precise definition of the data policy may be additionally supplied within the metadata.
     *                         In all cases it shall be the responsibility of the data consumer to ensure that they understand the data policy specified
     *                         by the data provider – which may necessitate dialogue with the data publisher for confirmation of terms and conditions.
     *                     
     * 
     */
    @XmlEnumValue("WMOOther")
    WMO_OTHER("WMOOther");
    private final String value;

    DataPolicyUseConstraintsType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataPolicyUseConstraintsType fromValue(String v) {
        for (DataPolicyUseConstraintsType c: DataPolicyUseConstraintsType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
