//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for Domain_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Domain_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Atmospheric"/>
 *     &lt;enumeration value="Oceanic"/>
 *     &lt;enumeration value="Terrestrial"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Domain_Type")
@XmlEnum
public enum DomainType implements Serializable {

    @XmlEnumValue("Atmospheric")
    ATMOSPHERIC("Atmospheric"),
    @XmlEnumValue("Oceanic")
    OCEANIC("Oceanic"),
    @XmlEnumValue("Terrestrial")
    TERRESTRIAL("Terrestrial");
    private final String value;

    DomainType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DomainType fromValue(String v) {
        for (DomainType c: DomainType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
