//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for Environment_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Environment_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="surfaceCover" type="{}SurfaceCover_Type" minOccurs="0"/>
 *         &lt;element name="surfaceCoverClassificatioScheme" type="{}SurfaceCoverClassificatioScheme_Type" minOccurs="0"/>
 *         &lt;element name="topographyOrBathymetry" type="{}TopographyOrBathymetry_Type" minOccurs="0"/>
 *         &lt;element name="eventsAtStationPlatform" type="{}EventsAtStationPlatform_Type" minOccurs="0"/>
 *         &lt;element name="siteInformation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Environment_Type", propOrder = {
    "surfaceCover",
    "surfaceCoverClassificatioScheme",
    "topographyOrBathymetry",
    "eventsAtStationPlatform",
    "siteInformation"
})
public class EnvironmentType implements Serializable {

    protected SurfaceCoverType surfaceCover;
    protected SurfaceCoverClassificatioSchemeType surfaceCoverClassificatioScheme;
    protected TopographyOrBathymetryType topographyOrBathymetry;
    protected EventsAtStationPlatformType eventsAtStationPlatform;
    protected String siteInformation;

    /**
     * Gets the value of the surfaceCover property.
     * 
     * @return
     *     possible object is
     *     {@link SurfaceCoverType }
     *     
     */
    public SurfaceCoverType getSurfaceCover() {
        return surfaceCover;
    }

    /**
     * Sets the value of the surfaceCover property.
     * 
     * @param value
     *     allowed object is
     *     {@link SurfaceCoverType }
     *     
     */
    public void setSurfaceCover(SurfaceCoverType value) {
        this.surfaceCover = value;
    }

    /**
     * Gets the value of the surfaceCoverClassificatioScheme property.
     * 
     * @return
     *     possible object is
     *     {@link SurfaceCoverClassificatioSchemeType }
     *     
     */
    public SurfaceCoverClassificatioSchemeType getSurfaceCoverClassificatioScheme() {
        return surfaceCoverClassificatioScheme;
    }

    /**
     * Sets the value of the surfaceCoverClassificatioScheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link SurfaceCoverClassificatioSchemeType }
     *     
     */
    public void setSurfaceCoverClassificatioScheme(SurfaceCoverClassificatioSchemeType value) {
        this.surfaceCoverClassificatioScheme = value;
    }

    /**
     * Gets the value of the topographyOrBathymetry property.
     * 
     * @return
     *     possible object is
     *     {@link TopographyOrBathymetryType }
     *     
     */
    public TopographyOrBathymetryType getTopographyOrBathymetry() {
        return topographyOrBathymetry;
    }

    /**
     * Sets the value of the topographyOrBathymetry property.
     * 
     * @param value
     *     allowed object is
     *     {@link TopographyOrBathymetryType }
     *     
     */
    public void setTopographyOrBathymetry(TopographyOrBathymetryType value) {
        this.topographyOrBathymetry = value;
    }

    /**
     * Gets the value of the eventsAtStationPlatform property.
     * 
     * @return
     *     possible object is
     *     {@link EventsAtStationPlatformType }
     *     
     */
    public EventsAtStationPlatformType getEventsAtStationPlatform() {
        return eventsAtStationPlatform;
    }

    /**
     * Sets the value of the eventsAtStationPlatform property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventsAtStationPlatformType }
     *     
     */
    public void setEventsAtStationPlatform(EventsAtStationPlatformType value) {
        this.eventsAtStationPlatform = value;
    }

    /**
     * Gets the value of the siteInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteInformation() {
        return siteInformation;
    }

    /**
     * Sets the value of the siteInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteInformation(String value) {
        this.siteInformation = value;
    }

}
