//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for EventsAtStationPlatformNotFreeText_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EventsAtStationPlatformNotFreeText_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Grass-cutting"/>
 *     &lt;enumeration value="Snow clearing"/>
 *     &lt;enumeration value="Tree removal"/>
 *     &lt;enumeration value="Construction activity"/>
 *     &lt;enumeration value="Road work"/>
 *     &lt;enumeration value="Biomass burning"/>
 *     &lt;enumeration value="Dust storm"/>
 *     &lt;enumeration value="Storm damage"/>
 *     &lt;enumeration value="Wind storm"/>
 *     &lt;enumeration value="Flood"/>
 *     &lt;enumeration value="Fire"/>
 *     &lt;enumeration value="Earthquake"/>
 *     &lt;enumeration value="Land slide"/>
 *     &lt;enumeration value="Storm surge or tsunami"/>
 *     &lt;enumeration value="Lightning"/>
 *     &lt;enumeration value="Vandalism"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EventsAtStationPlatformNotFreeText_Type")
@XmlEnum
public enum EventsAtStationPlatformNotFreeTextType implements Serializable {

    @XmlEnumValue("Grass-cutting")
    GRASS_CUTTING("Grass-cutting"),
    @XmlEnumValue("Snow clearing")
    SNOW_CLEARING("Snow clearing"),
    @XmlEnumValue("Tree removal")
    TREE_REMOVAL("Tree removal"),
    @XmlEnumValue("Construction activity")
    CONSTRUCTION_ACTIVITY("Construction activity"),
    @XmlEnumValue("Road work")
    ROAD_WORK("Road work"),

    /**
     * 
     *                         Anthropogenic or natural
     *                     
     * 
     */
    @XmlEnumValue("Biomass burning")
    BIOMASS_BURNING("Biomass burning"),
    @XmlEnumValue("Dust storm")
    DUST_STORM("Dust storm"),
    @XmlEnumValue("Storm damage")
    STORM_DAMAGE("Storm damage"),
    @XmlEnumValue("Wind storm")
    WIND_STORM("Wind storm"),
    @XmlEnumValue("Flood")
    FLOOD("Flood"),
    @XmlEnumValue("Fire")
    FIRE("Fire"),
    @XmlEnumValue("Earthquake")
    EARTHQUAKE("Earthquake"),
    @XmlEnumValue("Land slide")
    LAND_SLIDE("Land slide"),
    @XmlEnumValue("Storm surge or tsunami")
    STORM_SURGE_OR_TSUNAMI("Storm surge or tsunami"),
    @XmlEnumValue("Lightning")
    LIGHTNING("Lightning"),
    @XmlEnumValue("Vandalism")
    VANDALISM("Vandalism");
    private final String value;

    EventsAtStationPlatformNotFreeTextType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EventsAtStationPlatformNotFreeTextType fromValue(String v) {
        for (EventsAtStationPlatformNotFreeTextType c: EventsAtStationPlatformNotFreeTextType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
