//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for ExposureOfInstruments_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExposureOfInstruments_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Class 1"/>
 *     &lt;enumeration value="Class 2"/>
 *     &lt;enumeration value="Class 3"/>
 *     &lt;enumeration value="Class 4"/>
 *     &lt;enumeration value="Class 5"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExposureOfInstruments_Type")
@XmlEnum
public enum ExposureOfInstrumentsType implements Serializable {


    /**
     * 
     *                         exposure of instrument allows reference level measurements
     *                     
     * 
     */
    @XmlEnumValue("Class 1")
    CLASS_1("Class 1"),

    /**
     * 
     *                         exposure of instrument has small or infrequence influence on measurement
     *                     
     * 
     */
    @XmlEnumValue("Class 2")
    CLASS_2("Class 2"),

    /**
     * 
     *                         exposure of instrument leads to increased uncertainty or occasional invalid measurements
     *                     
     * 
     */
    @XmlEnumValue("Class 3")
    CLASS_3("Class 3"),

    /**
     * 
     *                         exposure of instrument leads to high uncertainty or regular invalid measurements
     *                     
     * 
     */
    @XmlEnumValue("Class 4")
    CLASS_4("Class 4"),

    /**
     * 
     *                         exposure of instrument leads to invalid measurements
     *                     
     * 
     */
    @XmlEnumValue("Class 5")
    CLASS_5("Class 5");
    private final String value;

    ExposureOfInstrumentsType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExposureOfInstrumentsType fromValue(String v) {
        for (ExposureOfInstrumentsType c: ExposureOfInstrumentsType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
