//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * 
 *                 Position in space defining the location of the environmental monitoring station/platform at the time of observation.
 * 
 *                 NOTE 1: Required for fixed stations; for stations following
 *                 pre-determined trajectory (e.g. satellites);
 * 
 *                 NOTE 2: The elevation of a fixed terrestrial station is
 *                 defined as the height above sea level of the ground on
 *                 which the station stands (“Hha” in WMO Pub. 9 Vol A).
 * 
 *                 NOTE 3: The geospatial location can be a zero-, one-,
 *                 two-, or three-dimensional feature.
 * 
 *                 NOTE 4: Geographical coordinates can be specified in
 *                 decimal degrees. Latitudes are specified with reference to
 *                 the equator, with positive sign for latitudes north of the
 *                 equator, and negative sign for latitudes south of the
 *                 equator. Longitudes are specified with reference to the
 *                 Greenwich meridian, with positive sign for longitudes east
 *                 of Greenwich, and negative sign for meridians west of
 *                 Greenwich. Elevation is a signed number specified in
 *                 some distance measure (e.g., meters) relative to a
 *                 reference elevation, with positive sign in the direction
 *                 away from the Earth centre.
 * 
 *                 NOTE 5: The latitudinal and longitudinal positions of a
 *                 station referred to in the World Geodetic System 1984
 *                 (WGS-84) Earth Geodetic Model 1996 (EGM96) must be
 *                 recorded to a resolution of at least 0.001 decimal degrees
 *                 (WMO-No. 8, 2008, Part I, Chapter 1, 1.3.3.2).
 * 
 *                 NOTE 6: This element comprises 3 entities, the
 *                 coordinates (Lat/Long/Alt), the "geopositioning method"
 *                 (code table 11-01) which produced the coordinates, as
 *                 well as the "geospatial reference system" (code table
 *                 11-02) used.
 * 
 *                 EXAMPLES:
 *                 (i) The station Jungfraujoch is located at 46.54749°N
 *                 7.98509°E (3580.00 m a.m.s.l.). The reference system is
 *                 WGS-84.
 *                 (ii) Voluntary Observing Ship Route: WMO Regional
 *                 Association 5, Sub Area 6 (R56)
 *                 (iii) [geostationary satellite] Meteosat-8 (MSG-1) 3.6°E
 *                 (iv) [sun-synchronous satellite] NOAA-19 Height 870 km;
 *                 Local Solar Time (LST) 13:39
 *                 (v) Weather Watch Radar: Warruwi NT -11.6485° N,
 *                 133.3800 E, Height 19.1 m amsl.
 *                 (vi) River discharge gauge: Warrego River at Cunnamulla
 *                 Weir 28.1000 S, 145.6833 E, Height: 180 m amsl.
 *             
 * 
 * <p>Java class for GeospatialLocation_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeospatialLocation_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="coordinatesSourceDevice" type="{}CoordinatesSourceDevice_Type"/>
 *         &lt;element name="coordinatesReference" type="{}CoordinatesReference_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeospatialLocation_Type", propOrder = {
    "coordinatesSourceDevice",
    "coordinatesReference"
})
public class GeospatialLocationType implements Serializable {

    @XmlElement(required = true)
    protected CoordinatesSourceDeviceType coordinatesSourceDevice;
    @XmlElement(required = true)
    protected CoordinatesReferenceType coordinatesReference;

    /**
     * Gets the value of the coordinatesSourceDevice property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinatesSourceDeviceType }
     *     
     */
    public CoordinatesSourceDeviceType getCoordinatesSourceDevice() {
        return coordinatesSourceDevice;
    }

    /**
     * Sets the value of the coordinatesSourceDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinatesSourceDeviceType }
     *     
     */
    public void setCoordinatesSourceDevice(CoordinatesSourceDeviceType value) {
        this.coordinatesSourceDevice = value;
    }

    /**
     * Gets the value of the coordinatesReference property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinatesReferenceType }
     *     
     */
    public CoordinatesReferenceType getCoordinatesReference() {
        return coordinatesReference;
    }

    /**
     * Sets the value of the coordinatesReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinatesReferenceType }
     *     
     */
    public void setCoordinatesReference(CoordinatesReferenceType value) {
        this.coordinatesReference = value;
    }

}
