//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * 
 *                 Geospatial location of instrument/sensor.
 * 
 *                 NOTE 1:
 *                 Geographic location of instrument such as
 *                 airfield anemometer or transmissometer.
 * 
 *                 NOTE 2:
 *                 This element comprises 3 entities, the
 *                 coordinates (Lat/Long/Alt), the
 *                 "geopositioning method" (code table 11-01)
 *                 which produced the coordinates, as well as
 *                 the "geospatial reference system" (code table
 *                 11-02) used.
 * 
 *                 EXAMPLES:
 *                 1) Melbourne Airport AU (East anemometer)
 *                 –37.6602 N, 144.8443 E, 122.00 m amsl.
 *                 2) relative position of wind sensor aboard
 *                 ship
 *                 3) 30 km upstream of river mouth
 *             
 * 
 * <p>Java class for GeospatialLocation_Instruments_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeospatialLocation_Instruments_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="coordinatesSourceDevice" type="{}CoordinatesSourceDevice_Type"/>
 *         &lt;element name="coordinatesReference" type="{}CoordinatesReference_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeospatialLocation_Instruments_Type", propOrder = {
    "coordinatesSourceDevice",
    "coordinatesReference"
})
public class GeospatialLocationInstrumentsType implements Serializable {

    @XmlElement(required = true)
    protected CoordinatesSourceDeviceType coordinatesSourceDevice;
    @XmlElement(required = true)
    protected CoordinatesReferenceType coordinatesReference;

    /**
     * Gets the value of the coordinatesSourceDevice property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinatesSourceDeviceType }
     *     
     */
    public CoordinatesSourceDeviceType getCoordinatesSourceDevice() {
        return coordinatesSourceDevice;
    }

    /**
     * Sets the value of the coordinatesSourceDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinatesSourceDeviceType }
     *     
     */
    public void setCoordinatesSourceDevice(CoordinatesSourceDeviceType value) {
        this.coordinatesSourceDevice = value;
    }

    /**
     * Gets the value of the coordinatesReference property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinatesReferenceType }
     *     
     */
    public CoordinatesReferenceType getCoordinatesReference() {
        return coordinatesReference;
    }

    /**
     * Sets the value of the coordinatesReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinatesReferenceType }
     *     
     */
    public void setCoordinatesReference(CoordinatesReferenceType value) {
        this.coordinatesReference = value;
    }

}
