//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for InstrumentControlResult_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InstrumentControlResult_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="no changes - in calibration"/>
 *     &lt;enumeration value="no changes - out of calibration"/>
 *     &lt;enumeration value="no changes – calibration unknown"/>
 *     &lt;enumeration value="recalibrated - in calibration"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InstrumentControlResult_Type")
@XmlEnum
public enum InstrumentControlResultType implements Serializable {


    /**
     * 
     *                         Instrument verified and found to be in calibration
     *                     
     * 
     */
    @XmlEnumValue("no changes - in calibration")
    NO_CHANGES_IN_CALIBRATION("no changes - in calibration"),

    /**
     * 
     *                         Instrument checked and found to be out of calibration; no changes to calibration function
     *                     
     * 
     */
    @XmlEnumValue("no changes - out of calibration")
    NO_CHANGES_OUT_OF_CALIBRATION("no changes - out of calibration"),

    /**
     * 
     *                         Instrument visited but calibration could not be carried out
     *                     
     * 
     */
    @XmlEnumValue("no changes \u2013 calibration unknown")
    NO_CHANGES_CALIBRATION_UNKNOWN("no changes \u2013 calibration unknown"),

    /**
     * 
     *                         Instrument checked and found to be out of calibration; instrument recalibrated (calibration function changed)
     *                     
     * 
     */
    @XmlEnumValue("recalibrated - in calibration")
    RECALIBRATED_IN_CALIBRATION("recalibrated - in calibration");
    private final String value;

    InstrumentControlResultType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InstrumentControlResultType fromValue(String v) {
        for (InstrumentControlResultType c: InstrumentControlResultType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
