//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for InstrumentOperatingStatus_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InstrumentOperatingStatus_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Operational"/>
 *     &lt;enumeration value="Testing"/>
 *     &lt;enumeration value="Not in service"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InstrumentOperatingStatus_Type")
@XmlEnum
public enum InstrumentOperatingStatusType implements Serializable {


    /**
     * 
     *                         The instrument is declared operational and subject to routine maintenance
     *                     
     * 
     */
    @XmlEnumValue("Operational")
    OPERATIONAL("Operational"),

    /**
     * 
     *                         The instrument is deployed for testing purposes and the information provided may not be reliable
     *                     
     * 
     */
    @XmlEnumValue("Testing")
    TESTING("Testing"),

    /**
     * 
     *                         The instrument is deployed but presently not in service
     *                     
     * 
     */
    @XmlEnumValue("Not in service")
    NOT_IN_SERVICE("Not in service");
    private final String value;

    InstrumentOperatingStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InstrumentOperatingStatusType fromValue(String v) {
        for (InstrumentOperatingStatusType c: InstrumentOperatingStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
