//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for LocalTopography_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LocalTopography_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Not applicable"/>
 *     &lt;enumeration value="Hilltop"/>
 *     &lt;enumeration value="Ridge"/>
 *     &lt;enumeration value="Slope"/>
 *     &lt;enumeration value="Flat"/>
 *     &lt;enumeration value="Valley bottom"/>
 *     &lt;enumeration value="Depression"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LocalTopography_Type")
@XmlEnum
public enum LocalTopographyType implements Serializable {


    /**
     * 
     *                         None of the codes in the table are applicable in the context of this particular observation (nilReason)
     *                     
     * 
     */
    @XmlEnumValue("Not applicable")
    NOT_APPLICABLE("Not applicable"),

    /**
     * 
     *                         Higher than all or nearly all of the surrounding land or subsurface.
     *                     
     * 
     */
    @XmlEnumValue("Hilltop")
    HILLTOP("Hilltop"),

    /**
     * 
     *                         Higher than all or nearly all of the surrounding land or subsurface, but elongated and extending beyond a 50 m radius.
     *                     
     * 
     */
    @XmlEnumValue("Ridge")
    RIDGE("Ridge"),

    /**
     * 
     *                         Neither crest nor depression or valley bottom, and with a slope more than 3%.
     *                     
     * 
     */
    @XmlEnumValue("Slope")
    SLOPE("Slope"),

    /**
     * 
     *                         Slope less than 3% and not a top, ridge, valley bottom or depression. Use for plains.
     *                     
     * 
     */
    @XmlEnumValue("Flat")
    FLAT("Flat"),

    /**
     * 
     *                         Lower than nearly all of surrounding land or subsurface, but water can flow out.
     *                     
     * 
     */
    @XmlEnumValue("Valley bottom")
    VALLEY_BOTTOM("Valley bottom"),

    /**
     * 
     *                         Lower than surrounding land or subsurface, with no above-ground outlet for water.
     *                     
     * 
     */
    @XmlEnumValue("Depression")
    DEPRESSION("Depression");
    private final String value;

    LocalTopographyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LocalTopographyType fromValue(String v) {
        for (LocalTopographyType c: LocalTopographyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
