//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for ModeOfObservation_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ModeOfObservation_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="V"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ModeOfObservation_Type")
@XmlEnum
public enum ModeOfObservationType implements Serializable {


    /**
     * 
     *                         Instantaneous
     *                     
     * 
     */
    I,

    /**
     * 
     *                         Total
     *                     
     * 
     */
    T,

    /**
     * 
     *                         Variability
     *                     
     * 
     */
    V;

    public String value() {
        return name();
    }

    public static ModeOfObservationType fromValue(String v) {
        return valueOf(v);
    }

}
