//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * 
 *                 Specifies the basic characteristics of the observed variable and the resulting datasets. It includes an element describing the spatial
 *                 representativeness of the observation as well as the biogeophysical compartment the observation describe.
 *             
 * 
 * <p>Java class for ObservedVariable_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObservedVariable_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="observedVariable-measurand" type="{}ObservedVariable-measurand_Type"/>
 *         &lt;element name="measurementUnit" type="{}MeasurementUnit_Type" minOccurs="0"/>
 *         &lt;element name="temporalExtent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="spatialExtent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="representativenessOfObservation" type="{}Representativeness_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObservedVariable_Type", propOrder = {
    "observedVariableMeasurand",
    "measurementUnit",
    "temporalExtent",
    "spatialExtent",
    "representativenessOfObservation"
})
public class ObservedVariableType  implements Serializable {

    @XmlElement(name = "observedVariable-measurand", required = true)
    protected ObservedVariableMeasurandType observedVariableMeasurand;
    protected MeasurementUnitType measurementUnit;
    @XmlElement(required = true)
    protected String temporalExtent;
    @XmlElement(required = true)
    protected String spatialExtent;
    protected RepresentativenessType representativenessOfObservation;

    /**
     * Gets the value of the observedVariableMeasurand property.
     * 
     * @return
     *     possible object is
     *     {@link ObservedVariableMeasurandType }
     *     
     */
    public ObservedVariableMeasurandType getObservedVariableMeasurand() {
        return observedVariableMeasurand;
    }

    /**
     * Sets the value of the observedVariableMeasurand property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservedVariableMeasurandType }
     *     
     */
    public void setObservedVariableMeasurand(ObservedVariableMeasurandType value) {
        this.observedVariableMeasurand = value;
    }

    /**
     * Gets the value of the measurementUnit property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementUnitType }
     *     
     */
    public MeasurementUnitType getMeasurementUnit() {
        return measurementUnit;
    }

    /**
     * Sets the value of the measurementUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementUnitType }
     *     
     */
    public void setMeasurementUnit(MeasurementUnitType value) {
        this.measurementUnit = value;
    }

    /**
     * Gets the value of the temporalExtent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemporalExtent() {
        return temporalExtent;
    }

    /**
     * Sets the value of the temporalExtent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemporalExtent(String value) {
        this.temporalExtent = value;
    }

    /**
     * Gets the value of the spatialExtent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpatialExtent() {
        return spatialExtent;
    }

    /**
     * Sets the value of the spatialExtent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpatialExtent(String value) {
        this.spatialExtent = value;
    }

    /**
     * Gets the value of the representativenessOfObservation property.
     * 
     * @return
     *     possible object is
     *     {@link RepresentativenessType }
     *     
     */
    public RepresentativenessType getRepresentativenessOfObservation() {
        return representativenessOfObservation;
    }

    /**
     * Sets the value of the representativenessOfObservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepresentativenessType }
     *     
     */
    public void setRepresentativenessOfObservation(RepresentativenessType value) {
        this.representativenessOfObservation = value;
    }

}
