//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * 
 *                 Specifies who is responsible for the observation and owns it.
 *             
 * 
 * <p>Java class for OwnershipAndDataPolicy_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OwnershipAndDataPolicy_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="supervisingOrganization" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dataPolicyUseConstraints" type="{}DataPolicyUseConstraints_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OwnershipAndDataPolicy_Type", propOrder = {
    "supervisingOrganization",
    "dataPolicyUseConstraints"
})
public class OwnershipAndDataPolicyType  implements Serializable {

    @XmlElement(required = true)
    protected String supervisingOrganization;
    @XmlElement(required = true)
    protected DataPolicyUseConstraintsType dataPolicyUseConstraints;

    /**
     * Gets the value of the supervisingOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupervisingOrganization() {
        return supervisingOrganization;
    }

    /**
     * Sets the value of the supervisingOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupervisingOrganization(String value) {
        this.supervisingOrganization = value;
    }

    /**
     * Gets the value of the dataPolicyUseConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link DataPolicyUseConstraintsType }
     *     
     */
    public DataPolicyUseConstraintsType getDataPolicyUseConstraints() {
        return dataPolicyUseConstraints;
    }

    /**
     * Sets the value of the dataPolicyUseConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataPolicyUseConstraintsType }
     *     
     */
    public void setDataPolicyUseConstraints(DataPolicyUseConstraintsType value) {
        this.dataPolicyUseConstraints = value;
    }

}
