//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * 
 *                 Specifies the main application area(s) of the observation and the observing programme(s) and networks
 *                 the observation is affiliated to.
 *             
 * 
 * <p>Java class for PurposeOfObservation_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PurposeOfObservation_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="applicationArea" type="{}ApplicationArea_Type"/>
 *         &lt;element name="programmeNetworkAffiliation" type="{}ProgrammeNetworkAffiliation_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PurposeOfObservation_Type", propOrder = {
    "applicationArea",
    "programmeNetworkAffiliation"
})
public class PurposeOfObservationType  implements Serializable {

    @XmlElement(required = true)
    protected ApplicationAreaType applicationArea;
    @XmlElement(required = true)
    protected ProgrammeNetworkAffiliationType programmeNetworkAffiliation;

    /**
     * Gets the value of the applicationArea property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationAreaType }
     *     
     */
    public ApplicationAreaType getApplicationArea() {
        return applicationArea;
    }

    /**
     * Sets the value of the applicationArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationAreaType }
     *     
     */
    public void setApplicationArea(ApplicationAreaType value) {
        this.applicationArea = value;
    }

    /**
     * Gets the value of the programmeNetworkAffiliation property.
     * 
     * @return
     *     possible object is
     *     {@link ProgrammeNetworkAffiliationType }
     *     
     */
    public ProgrammeNetworkAffiliationType getProgrammeNetworkAffiliation() {
        return programmeNetworkAffiliation;
    }

    /**
     * Sets the value of the programmeNetworkAffiliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgrammeNetworkAffiliationType }
     *     
     */
    public void setProgrammeNetworkAffiliation(ProgrammeNetworkAffiliationType value) {
        this.programmeNetworkAffiliation = value;
    }

}
