//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for QualityFlag_BUFR_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QualityFlag_BUFR_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Good"/>
 *     &lt;enumeration value="Inconsistent"/>
 *     &lt;enumeration value="Doubtful"/>
 *     &lt;enumeration value="Wrong"/>
 *     &lt;enumeration value="Not checked"/>
 *     &lt;enumeration value="Has been changed"/>
 *     &lt;enumeration value="Estimated"/>
 *     &lt;enumeration value="Missing value"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QualityFlag_BUFR_Type")
@XmlEnum
public enum QualityFlagBUFRType  implements Serializable {

    @XmlEnumValue("Good")
    GOOD("Good"),
    @XmlEnumValue("Inconsistent")
    INCONSISTENT("Inconsistent"),
    @XmlEnumValue("Doubtful")
    DOUBTFUL("Doubtful"),
    @XmlEnumValue("Wrong")
    WRONG("Wrong"),
    @XmlEnumValue("Not checked")
    NOT_CHECKED("Not checked"),
    @XmlEnumValue("Has been changed")
    HAS_BEEN_CHANGED("Has been changed"),
    @XmlEnumValue("Estimated")
    ESTIMATED("Estimated"),
    @XmlEnumValue("Missing value")
    MISSING_VALUE("Missing value");
    private final String value;

    QualityFlagBUFRType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QualityFlagBUFRType fromValue(String v) {
        for (QualityFlagBUFRType c: QualityFlagBUFRType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
