//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for QualityFlaggingSystem_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QualityFlaggingSystem_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Unknown"/>
 *     &lt;enumeration value="WMO BUFR table 0 33 020"/>
 *     &lt;enumeration value="Other quality flagging system"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QualityFlaggingSystem_Type")
@XmlEnum
public enum QualityFlaggingSystemType  implements Serializable {


    /**
     * 
     *                         Quality flag system not known
     *                     
     * 
     */
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown"),

    /**
     * 
     *                         http://codes.wmo.int/bufr4/codeflag/0-33-020
     *                     
     * 
     */
    @XmlEnumValue("WMO BUFR table 0 33 020")
    WMO_BUFR_TABLE_0_33_020("WMO BUFR table 0 33 020"),

    /**
     * 
     *                         Quality flags are specified according to another system
     *                     
     * 
     */
    @XmlEnumValue("Other quality flagging system")
    OTHER_QUALITY_FLAGGING_SYSTEM("Other quality flagging system");
    private final String value;

    QualityFlaggingSystemType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QualityFlaggingSystemType fromValue(String v) {
        for (QualityFlaggingSystemType c: QualityFlaggingSystemType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
