//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for QualityFlag_OGC_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QualityFlag_OGC_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Good"/>
 *     &lt;enumeration value="Suspect"/>
 *     &lt;enumeration value="Estimate"/>
 *     &lt;enumeration value="Poor"/>
 *     &lt;enumeration value="Unchecked"/>
 *     &lt;enumeration value="Missing"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QualityFlag_OGC_Type")
@XmlEnum
public enum QualityFlagOGCType  implements Serializable {


    /**
     * 
     *                         The data has been examined and represents a reliable measurement.
     *                     
     * 
     */
    @XmlEnumValue("Good")
    GOOD("Good"),

    /**
     * 
     *                         The data should be treated as suspect.
     *                     
     * 
     */
    @XmlEnumValue("Suspect")
    SUSPECT("Suspect"),

    /**
     * 
     *                         The data is an estimate only, not a direct measurement.
     *                     
     * 
     */
    @XmlEnumValue("Estimate")
    ESTIMATE("Estimate"),

    /**
     * 
     *                         The data should be considered as low quality and may have been rejected.
     *                     
     * 
     */
    @XmlEnumValue("Poor")
    POOR("Poor"),

    /**
     * 
     *                         The data has not been checked by any qualitative method.
     *                     
     * 
     */
    @XmlEnumValue("Unchecked")
    UNCHECKED("Unchecked"),

    /**
     * 
     *                         The data is missing.
     *                     
     * 
     */
    @XmlEnumValue("Missing")
    MISSING("Missing");
    private final String value;

    QualityFlagOGCType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QualityFlagOGCType fromValue(String v) {
        for (QualityFlagOGCType c: QualityFlagOGCType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
