//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for ReferenceTime_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReferenceTime_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Unknown"/>
 *     &lt;enumeration value="Time Server"/>
 *     &lt;enumeration value="Radio Clock"/>
 *     &lt;enumeration value="Manual Comparison"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReferenceTime_Type")
@XmlEnum
public enum ReferenceTimeType  implements Serializable {

    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown"),
    @XmlEnumValue("Time Server")
    TIME_SERVER("Time Server"),
    @XmlEnumValue("Radio Clock")
    RADIO_CLOCK("Radio Clock"),
    @XmlEnumValue("Manual Comparison")
    MANUAL_COMPARISON("Manual Comparison");
    private final String value;

    ReferenceTimeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReferenceTimeType fromValue(String v) {
        for (ReferenceTimeType c: ReferenceTimeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
