//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for RegionOfOriginOfData_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RegionOfOriginOfData_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="II"/>
 *     &lt;enumeration value="III"/>
 *     &lt;enumeration value="IV"/>
 *     &lt;enumeration value="V"/>
 *     &lt;enumeration value="VI"/>
 *     &lt;enumeration value="VII"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RegionOfOriginOfData_Type")
@XmlEnum
public enum RegionOfOriginOfDataType  implements Serializable {


    /**
     * 
     *                         Africa
     *                     
     * 
     */
    I,

    /**
     * 
     *                         Asia
     *                     
     * 
     */
    II,

    /**
     * 
     *                         South America
     *                     
     * 
     */
    III,

    /**
     * 
     *                         North America, Central America and the Caribbean
     *                     
     * 
     */
    IV,

    /**
     * 
     *                         South-West Pacific
     *                     
     * 
     */
    V,

    /**
     * 
     *                         Europe
     *                     
     * 
     */
    VI,

    /**
     * 
     *                         Antarctica
     *                     
     * 
     */
    VII;

    public String value() {
        return name();
    }

    public static RegionOfOriginOfDataType fromValue(String v) {
        return valueOf(v);
    }

}
