//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for RelativeElevation_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RelativeElevation_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Not applicable"/>
 *     &lt;enumeration value="Lowest"/>
 *     &lt;enumeration value="Low"/>
 *     &lt;enumeration value="Middle"/>
 *     &lt;enumeration value="High"/>
 *     &lt;enumeration value="Highest"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RelativeElevation_Type")
@XmlEnum
public enum RelativeElevationType  implements Serializable {


    /**
     * 
     *                         None of the codes in the table are applicable in the context of this particular observation (nilReason)
     *                     
     * 
     */
    @XmlEnumValue("Not applicable")
    NOT_APPLICABLE("Not applicable"),

    /**
     * 
     *                         In the bottom 5% of the elevation range
     *                     
     * 
     */
    @XmlEnumValue("Lowest")
    LOWEST("Lowest"),

    /**
     * 
     *                         Between 5% and 25% of the elevation range
     *                     
     * 
     */
    @XmlEnumValue("Low")
    LOW("Low"),

    /**
     * 
     *                         Between 25% and 75% of the elevation range
     *                     
     * 
     */
    @XmlEnumValue("Middle")
    MIDDLE("Middle"),

    /**
     * 
     *                         Between 75% and 95% of the elevation range
     *                     
     * 
     */
    @XmlEnumValue("High")
    HIGH("High"),

    /**
     * 
     *                         In the highest 5% of the elevation range
     *                     
     * 
     */
    @XmlEnumValue("Highest")
    HIGHEST("Highest");
    private final String value;

    RelativeElevationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RelativeElevationType fromValue(String v) {
        for (RelativeElevationType c: RelativeElevationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
