//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for Sampling_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Sampling_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="samplingProcedures" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sampleTreatment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="samplingStrategy" type="{}SamplingStrategy_Type" minOccurs="0"/>
 *         &lt;element name="samplingTimePeriod" type="{}MeaningOfTimeStamp_Type"/>
 *         &lt;element name="spatialSamplingResolution" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="temporalSamplingInterval" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="diurnalBaseTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scheduleOfObservation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Sampling_Type", propOrder = {
    "samplingProcedures",
    "sampleTreatment",
    "samplingStrategy",
    "samplingTimePeriod",
    "spatialSamplingResolution",
    "temporalSamplingInterval",
    "diurnalBaseTime",
    "scheduleOfObservation"
})
public class SamplingType  implements Serializable {

    protected String samplingProcedures;
    protected String sampleTreatment;
    protected SamplingStrategyType samplingStrategy;
    @XmlElement(required = true)
    protected MeaningOfTimeStampType samplingTimePeriod;
    @XmlElement(required = true)
    protected String spatialSamplingResolution;
    @XmlElement(required = true)
    protected String temporalSamplingInterval;
    @XmlElement(required = true)
    protected String diurnalBaseTime;
    @XmlElement(required = true)
    protected String scheduleOfObservation;

    /**
     * Gets the value of the samplingProcedures property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSamplingProcedures() {
        return samplingProcedures;
    }

    /**
     * Sets the value of the samplingProcedures property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSamplingProcedures(String value) {
        this.samplingProcedures = value;
    }

    /**
     * Gets the value of the sampleTreatment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleTreatment() {
        return sampleTreatment;
    }

    /**
     * Sets the value of the sampleTreatment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleTreatment(String value) {
        this.sampleTreatment = value;
    }

    /**
     * Gets the value of the samplingStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link SamplingStrategyType }
     *     
     */
    public SamplingStrategyType getSamplingStrategy() {
        return samplingStrategy;
    }

    /**
     * Sets the value of the samplingStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamplingStrategyType }
     *     
     */
    public void setSamplingStrategy(SamplingStrategyType value) {
        this.samplingStrategy = value;
    }

    /**
     * Gets the value of the samplingTimePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link MeaningOfTimeStampType }
     *     
     */
    public MeaningOfTimeStampType getSamplingTimePeriod() {
        return samplingTimePeriod;
    }

    /**
     * Sets the value of the samplingTimePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeaningOfTimeStampType }
     *     
     */
    public void setSamplingTimePeriod(MeaningOfTimeStampType value) {
        this.samplingTimePeriod = value;
    }

    /**
     * Gets the value of the spatialSamplingResolution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpatialSamplingResolution() {
        return spatialSamplingResolution;
    }

    /**
     * Sets the value of the spatialSamplingResolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpatialSamplingResolution(String value) {
        this.spatialSamplingResolution = value;
    }

    /**
     * Gets the value of the temporalSamplingInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemporalSamplingInterval() {
        return temporalSamplingInterval;
    }

    /**
     * Sets the value of the temporalSamplingInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemporalSamplingInterval(String value) {
        this.temporalSamplingInterval = value;
    }

    /**
     * Gets the value of the diurnalBaseTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiurnalBaseTime() {
        return diurnalBaseTime;
    }

    /**
     * Sets the value of the diurnalBaseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiurnalBaseTime(String value) {
        this.diurnalBaseTime = value;
    }

    /**
     * Gets the value of the scheduleOfObservation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheduleOfObservation() {
        return scheduleOfObservation;
    }

    /**
     * Sets the value of the scheduleOfObservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduleOfObservation(String value) {
        this.scheduleOfObservation = value;
    }

}
