//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for SourceOfObservation_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SourceOfObservation_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Automatic observation"/>
 *     &lt;enumeration value="Manual observation"/>
 *     &lt;enumeration value="Visual observation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SourceOfObservation_Type")
@XmlEnum
public enum SourceOfObservationType  implements Serializable {


    /**
     * 
     *                         Automatically produced measurement result
     *                     
     * 
     */
    @XmlEnumValue("Automatic observation")
    AUTOMATIC_OBSERVATION("Automatic observation"),

    /**
     * 
     *                         Manual reading of instrument
     *                     
     * 
     */
    @XmlEnumValue("Manual observation")
    MANUAL_OBSERVATION("Manual observation"),

    /**
     * 
     *                         Human, non-instrumented observation
     *                     
     * 
     */
    @XmlEnumValue("Visual observation")
    VISUAL_OBSERVATION("Visual observation");
    private final String value;

    SourceOfObservationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SourceOfObservationType fromValue(String v) {
        for (SourceOfObservationType c: SourceOfObservationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
