//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for StationPlatformType_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StationPlatformType_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="land station"/>
 *     &lt;enumeration value="sea station"/>
 *     &lt;enumeration value="aircraft"/>
 *     &lt;enumeration value="satellite"/>
 *     &lt;enumeration value="underwater platform"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StationPlatformType_Type")
@XmlEnum
public enum StationPlatformTypeType  implements Serializable {


    /**
     * 
     *                         An observing station or field site situated on land, either fixed or mobile.
     *                     
     * 
     */
    @XmlEnumValue("land station")
    LAND_STATION("land station"),

    /**
     * 
     *                         An observing station situated at sea. Sea stations include ships, ocean weather stations and stations on fixed
     *                         or drifting platforms (rigs, platforms, lightships, buoys and ice floes).
     *                     
     * 
     */
    @XmlEnumValue("sea station")
    SEA_STATION("sea station"),

    /**
     * 
     *                         An airplane, helicopter or airship used to make environmental observations.
     *                     
     * 
     */
    @XmlEnumValue("aircraft")
    AIRCRAFT("aircraft"),

    /**
     * 
     *                         A platform placed in orbit around the earth to make environmental observations.
     *                     
     * 
     */
    @XmlEnumValue("satellite")
    SATELLITE("satellite"),

    /**
     * 
     *                         A platform under a lake or sea surface, including autonomous underwater vehicles.
     *                     
     * 
     */
    @XmlEnumValue("underwater platform")
    UNDERWATER_PLATFORM("underwater platform");
    private final String value;

    StationPlatformTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StationPlatformTypeType fromValue(String v) {
        for (StationPlatformTypeType c: StationPlatformTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
