//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for StatusOfObservation_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StatusOfObservation_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Primary"/>
 *     &lt;enumeration value="Additional"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StatusOfObservation_Type")
@XmlEnum
public enum StatusOfObservationType  implements Serializable {


    /**
     * 
     *                         The primary or official observation of the observed variable
     *                     
     * 
     */
    @XmlEnumValue("Primary")
    PRIMARY("Primary"),

    /**
     * 
     *                         Additional or supplemented observation of the observed variable
     *                     
     * 
     */
    @XmlEnumValue("Additional")
    ADDITIONAL("Additional");
    private final String value;

    StatusOfObservationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StatusOfObservationType fromValue(String v) {
        for (StatusOfObservationType c: StatusOfObservationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
