//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Subdomain_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Subdomain_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Temperature"/>
 *     &lt;enumeration value="Water vapour"/>
 *     &lt;enumeration value="Carbon dioxide"/>
 *     &lt;enumeration value="Methane"/>
 *     &lt;enumeration value="Ozone"/>
 *     &lt;enumeration value="Aerosols"/>
 *     &lt;enumeration value="Carbon Monoxide"/>
 *     &lt;enumeration value="Formaldehyde"/>
 *     &lt;enumeration value="Nitrogen Dioxide"/>
 *     &lt;enumeration value="VOCs"/>
 *     &lt;enumeration value="Black and brown carbon"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Subdomain_Type")
@XmlEnum
public enum SubdomainType {

    @XmlEnumValue("Temperature")
    TEMPERATURE("Temperature"),
    @XmlEnumValue("Water vapour")
    WATER_VAPOUR("Water vapour"),
    @XmlEnumValue("Carbon dioxide")
    CARBON_DIOXIDE("Carbon dioxide"),
    @XmlEnumValue("Methane")
    METHANE("Methane"),
    @XmlEnumValue("Ozone")
    OZONE("Ozone"),
    @XmlEnumValue("Aerosols")
    AEROSOLS("Aerosols"),
    @XmlEnumValue("Carbon Monoxide")
    CARBON_MONOXIDE("Carbon Monoxide"),
    @XmlEnumValue("Formaldehyde")
    FORMALDEHYDE("Formaldehyde"),
    @XmlEnumValue("Nitrogen Dioxide")
    NITROGEN_DIOXIDE("Nitrogen Dioxide"),
    @XmlEnumValue("VOCs")
    VO_CS("VOCs"),
    @XmlEnumValue("Black and brown carbon")
    BLACK_AND_BROWN_CARBON("Black and brown carbon"),
    @XmlEnumValue("Atmospheric Pressure")
    ATMOSPHERIC_PRESSURE("Atmospheric Pressure"),
    @XmlEnumValue("Wind")
    WIND("Wind"),
    @XmlEnumValue("Global Downward Solar Radiation")
    GLOBAL_DOWNWARD_SOLAR_RADIATION("Global Downward Solar Radiation");
    private final String value;

    SubdomainType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SubdomainType fromValue(String v) {
        for (SubdomainType c: SubdomainType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
