//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * 
 *                 The observed (bio)physical cover on the Earth’s surface in the vicinity of the observation.
 * 
 *                 NOTE 1:
 *                 To be applied to 3 different geographic scales of the vicinity of the
 *                 observation, namely horizontal radii of <100 m, of 100 m to 3 km, and
 *                 of 3 km to 100 km.
 * 
 *                 NOTE 2:
 *                 Surface cover or land cover is distinct from land use despite the two
 *                 terms often being used interchangeably. Land use is a description of
 *                 how people utilize the land and socio-economic activity – urban and
 *                 agricultural land uses are two of the most commonly known land use
 *                 classes. At any one point or place, there may be multiple and
 *                 alternate land uses, the specification of which may have a political
 *                 dimension (Wikipedia, 2013).
 * 
 *                 NOTE 3:
 *                 There are various classification methods for ‘land cover’. The MODIS
 *                 product MCD12Q1 provides 5 different classifications on 500 m
 *                 resolution grid
 *                 (https://lpdaac.usgs.gov/products/modis_products_table/mcd12q1).
 *                 These include the IGBP, UMD, LAI/fPAR, NPP and PFT
 *                 classifications.
 * 
 *                 NOTE 4:
 *                 An alternative approach is the ‘Land Cover Classification System’
 *                 (LCCS) adopted by the Food and Agriculture Organization of the
 *                 United Nations. Translation of other systems to LCCS has been
 *                 explored by Herold et al. (2009). Eight major land cover types are
 *                 identified during the first, dichotomous classification phase. These are
 *                 refined in a subsequent so-called Modular-Hierarchical Phase, in
 *                 which land cover classes are created by the combination of sets of
 *                 pre-defined classifiers. These classifiers are tailored to each of the
 *                 eight major land cover types. This process can be supported by
 *                 software (http://www.glcn.org/sof_7_en.jsp) or manually using a field
 *                 log sheet
 *                 (http://commons.wikimedia.org/wiki/File:LCCS_field_protokoll.png)
 *             
 * 
 * <p>Java class for SurfaceCover_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SurfaceCover_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="landCoverTypes_IGBP" type="{}LandCoverTypes_IGBP_Type" minOccurs="0"/>
 *         &lt;element name="landCoverTypes_UMD" type="{}LandCoverTypes_UMD_Type" minOccurs="0"/>
 *         &lt;element name="landCoverTypes_LAI_fPAR" type="{}landCoverTypes_LAI_fPAR_Type" minOccurs="0"/>
 *         &lt;element name="landCoverTypes_NPP" type="{}landCoverTypes_NPP_Type" minOccurs="0"/>
 *         &lt;element name="landCoverTypes_PFT" type="{}landCoverTypes_PFT_Type" minOccurs="0"/>
 *         &lt;element name="landCoverTypes_LCCS" type="{}landCoverTypes_LCCS_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SurfaceCover_Type", propOrder = {
    "landCoverTypesIGBP",
    "landCoverTypesUMD",
    "landCoverTypesLAIFPAR",
    "landCoverTypesNPP",
    "landCoverTypesPFT",
    "landCoverTypesLCCS"
})
public class SurfaceCoverType implements Serializable {

    @XmlElement(name = "landCoverTypes_IGBP")
    protected LandCoverTypesIGBPType landCoverTypesIGBP;
    @XmlElement(name = "landCoverTypes_UMD")
    protected LandCoverTypesUMDType landCoverTypesUMD;
    @XmlElement(name = "landCoverTypes_LAI_fPAR")
    protected LandCoverTypesLAIFPARType landCoverTypesLAIFPAR;
    @XmlElement(name = "landCoverTypes_NPP")
    protected LandCoverTypesNPPType landCoverTypesNPP;
    @XmlElement(name = "landCoverTypes_PFT")
    protected LandCoverTypesPFTType landCoverTypesPFT;
    @XmlElement(name = "landCoverTypes_LCCS")
    protected LandCoverTypesLCCSType landCoverTypesLCCS;

    /**
     * Gets the value of the landCoverTypesIGBP property.
     * 
     * @return
     *     possible object is
     *     {@link LandCoverTypesIGBPType }
     *     
     */
    public LandCoverTypesIGBPType getLandCoverTypesIGBP() {
        return landCoverTypesIGBP;
    }

    /**
     * Sets the value of the landCoverTypesIGBP property.
     * 
     * @param value
     *     allowed object is
     *     {@link LandCoverTypesIGBPType }
     *     
     */
    public void setLandCoverTypesIGBP(LandCoverTypesIGBPType value) {
        this.landCoverTypesIGBP = value;
    }

    /**
     * Gets the value of the landCoverTypesUMD property.
     * 
     * @return
     *     possible object is
     *     {@link LandCoverTypesUMDType }
     *     
     */
    public LandCoverTypesUMDType getLandCoverTypesUMD() {
        return landCoverTypesUMD;
    }

    /**
     * Sets the value of the landCoverTypesUMD property.
     * 
     * @param value
     *     allowed object is
     *     {@link LandCoverTypesUMDType }
     *     
     */
    public void setLandCoverTypesUMD(LandCoverTypesUMDType value) {
        this.landCoverTypesUMD = value;
    }

    /**
     * Gets the value of the landCoverTypesLAIFPAR property.
     * 
     * @return
     *     possible object is
     *     {@link LandCoverTypesLAIFPARType }
     *     
     */
    public LandCoverTypesLAIFPARType getLandCoverTypesLAIFPAR() {
        return landCoverTypesLAIFPAR;
    }

    /**
     * Sets the value of the landCoverTypesLAIFPAR property.
     * 
     * @param value
     *     allowed object is
     *     {@link LandCoverTypesLAIFPARType }
     *     
     */
    public void setLandCoverTypesLAIFPAR(LandCoverTypesLAIFPARType value) {
        this.landCoverTypesLAIFPAR = value;
    }

    /**
     * Gets the value of the landCoverTypesNPP property.
     * 
     * @return
     *     possible object is
     *     {@link LandCoverTypesNPPType }
     *     
     */
    public LandCoverTypesNPPType getLandCoverTypesNPP() {
        return landCoverTypesNPP;
    }

    /**
     * Sets the value of the landCoverTypesNPP property.
     * 
     * @param value
     *     allowed object is
     *     {@link LandCoverTypesNPPType }
     *     
     */
    public void setLandCoverTypesNPP(LandCoverTypesNPPType value) {
        this.landCoverTypesNPP = value;
    }

    /**
     * Gets the value of the landCoverTypesPFT property.
     * 
     * @return
     *     possible object is
     *     {@link LandCoverTypesPFTType }
     *     
     */
    public LandCoverTypesPFTType getLandCoverTypesPFT() {
        return landCoverTypesPFT;
    }

    /**
     * Sets the value of the landCoverTypesPFT property.
     * 
     * @param value
     *     allowed object is
     *     {@link LandCoverTypesPFTType }
     *     
     */
    public void setLandCoverTypesPFT(LandCoverTypesPFTType value) {
        this.landCoverTypesPFT = value;
    }

    /**
     * Gets the value of the landCoverTypesLCCS property.
     * 
     * @return
     *     possible object is
     *     {@link LandCoverTypesLCCSType }
     *     
     */
    public LandCoverTypesLCCSType getLandCoverTypesLCCS() {
        return landCoverTypesLCCS;
    }

    /**
     * Sets the value of the landCoverTypesLCCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link LandCoverTypesLCCSType }
     *     
     */
    public void setLandCoverTypesLCCS(LandCoverTypesLCCSType value) {
        this.landCoverTypesLCCS = value;
    }

}
