//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 04:39:49 PM CET 
//


package cnr.imaa.model.wigos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for TopographicContext_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TopographicContext_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Not applicable"/>
 *     &lt;enumeration value="Plains"/>
 *     &lt;enumeration value="Hollows"/>
 *     &lt;enumeration value="Rises"/>
 *     &lt;enumeration value="Valleys"/>
 *     &lt;enumeration value="Hills"/>
 *     &lt;enumeration value="Mountains"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TopographicContext_Type")
@XmlEnum
public enum TopographicContextType implements Serializable {


    /**
     * 
     *                         None of the codes in the table are applicable in the context of this particular observation (nilReason)
     *                     
     * 
     */
    @XmlEnumValue("Not applicable")
    NOT_APPLICABLE("Not applicable"),

    /**
     * 
     *                         Very low relief
     *                     
     * 
     */
    @XmlEnumValue("Plains")
    PLAINS("Plains"),

    /**
     * 
     *                         Low relief, tending to convergent form
     *                     
     * 
     */
    @XmlEnumValue("Hollows")
    HOLLOWS("Hollows"),

    /**
     * 
     *                         Low relief, tending to divergent form
     *                     
     * 
     */
    @XmlEnumValue("Rises")
    RISES("Rises"),

    /**
     * 
     *                         Medium relief, tending to convergent form
     *                     
     * 
     */
    @XmlEnumValue("Valleys")
    VALLEYS("Valleys"),

    /**
     * 
     *                         Medium relief, tending to divergent form
     *                     
     * 
     */
    @XmlEnumValue("Hills")
    HILLS("Hills"),

    /**
     * 
     *                         High relief
     *                     
     * 
     */
    @XmlEnumValue("Mountains")
    MOUNTAINS("Mountains");
    private final String value;

    TopographicContextType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TopographicContextType fromValue(String v) {
        for (TopographicContextType c: TopographicContextType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
